label = ADER
model_type = ader
model_path = .data\save\model_valid_best
tokenizer_path = .data\save\model_valid_best
dataset_path = .data\datasets\test.json
types_path = .data\datasets\types.json
eval_batch_size = 1
rel_filter_threshold = 0.6
size_embedding = 25
prop_drop = 0.1
max_span_size = 6
store_predictions = true
store_examples = false
sampling_processes = 4
max_pairs = 400
lowercase = true
log_path = .data\log