label = ADER
model_type = ader
model_path = ./data/models/BioLinkBERT
tokenizer_path = ./data/models/BioLinkBERT
train_path = ./data/datasets/train.json
valid_path = ./data/datasets/dev.json
types_path = ./data/datasets/types.json
train_batch_size = 4
eval_batch_size = 1
neg_entity_count = 200
neg_relation_count = 400
epochs = 80
lr = 3e-5
lr_warmup = 0.1
weight_decay = 0.01
max_grad_norm = 1
rel_filter_threshold = 0.6
size_embedding = 25
prop_drop = 0.1
max_span_size = 6
store_predictions = true
store_examples = false
sampling_processes = 4
max_pairs = 400
final_eval = false
lowercase = true
log_path = .data\log
save_path = .data\save